
spring:
  application:
    name: icb-back
  devtools:
    livereload:
      enabled=true:
    restart:
      enabled=true:

logging:
  level:
    root: INFO
    WEB: INFO
    uk.go.hm: DEBUG

server:
  port: 8080
  connection-timeout: 5m
  tomcat:
    keep-alive-timeout: 5m
    apr-lifecycle-listener:
      enabled: false


app:
  dvla:
    delay: 2000
  lev:
    delay: 5000